# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v1.*

pool:
  vmImage: 'ubuntu-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

steps:
  - task: Cache@2
    inputs:
      key: 'gradle | "$(Agent.OS)"'
      restoreKeys: gradle
      path: $(GRADLE_USER_HOME)
    displayName: Gradle build cache
  - task: Gradle@3
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'buildPlugin'
    displayName: 'Build plugin'
  - task: GitHubRelease@1
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      gitHubConnection: 'GitHub Release'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      assets: 'build/distributions/*.zip'
      assetUploadMode: 'delete'
      tagSource: 'gitTag'
      target: '$(Build.SourceVersion)'
    displayName: 'Publish to GitHub Release'
  - task: Gradle@3
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      jdkVersionOption: '1.17'
      options: '-Djetbrains.token=$(jetbrains.token)'
      tasks: 'publishPlugin'
    displayName: 'Publish to JetBrains Plugin Repository'
